### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by justinwoo** [paf31/purescript-foreign-generic#18]
Maybe we should add examples like in other libraries like https://github.com/purescript/purescript-foreign? I realize this could be a total pain when introducing changes in the future, but I wouldn't mind being asked to update them.

I have some basic-ish examples in https://github.com/justinwoo/simple-record-foreign-generic-demo and https://github.com/justinwoo/purescript-howto-foreign-generic at least that I could work on porting to whatever format is most convenient.

**Comment by justinwoo** [comment]
Err, yeah, related to #17 definitely I guess, since either (or both) could be good.

**Comment by paf31** [comment]
Perhaps we could just link to you existing repos/egghead lesson?

**Comment by justinwoo** [comment]
Ha! Could work, but I think the Egghead lesson might eventually go out of date and my example repos would very easily get stale, unless we set something up to somehow run some tests on commits to this project?...

**Comment by paf31** [comment]
True  - well either way works. I'll gladly take a PR.
