### ISSUE TITLE
generic{De,En}code without requirement that every type has a Encode instance

### ISSUE THREAD

**Issue by wereHamster** [paf31/purescript-foreign-generic#24]
Previously it was possible to derive `Generic` instances of all my types and use `toForeignGeneric` to serialize the values. Now it seems that genericEncode/genericDecode require that every single type has a Decode/Encode instance, in addition to a Generic instance.

Even though we have dozens of types, this would be somewhat bearable, but we also use `Maybe` and other basic types which don't have Decode/Encode instances (why? is it intentional?). So now I need to write newtype wrappers around all the basic types so that I can attach Decode/Encode instances to them… and that's where I gave up.

Is there a reason why the new code requires Decode/Encode instances all the way down instead of relying on Generic alone?

**Comment by justinwoo** [comment]
`Maybe` is a fairly tricky case though... sometimes people want `null`, some want `undefined`/no props written/read. This library provides a [NullOrUndefined](https://pursuit.purescript.org/packages/purescript-foreign-generic/4.1.0/docs/Data.Foreign.NullOrUndefined#t:NullOrUndefined) type for working with optionally missing fields.

For all the other cases, I believe it was discussed before on IRC/Slack that just using generics-rep instances at any level would end up with confusion about the output... I think maybe this change might have been in purescript-foreign before coming here...

**Comment by wereHamster** [comment]
If users want a specific representation on the other side, by all means, let them use `NullOrUndefined` or their own wrappers. But I don't care about how the data is serialized. All I want is to be able to decode what I encoded previously, I don't even want stability across versions, I know that I'll be using the exact same code to for both encoding and decoding.

Also, previously we had `Data.Foreign.Null` and `Data.Foreign.Undefined`, now both are squashed into a single module so I can't easily say that I accept just `null` or just `undefined` but not both…

**Comment by paf31** [comment]
> Is there a reason why the new code requires Decode/Encode instances all the way down instead of relying on Generic alone?

The old version required `IsForeign` and `AsForeign` everywhere too, but those classes don't exist any more. Nothing has changed apart from that.

> Also, previously we had `Data.Foreign.Null` and `Data.Foreign.Undefined`

We can add them back. Would you like to send a PR?

**Comment by wereHamster** [comment]
In the old version I could do the following. Notice that there is no `AsForeign` instance for `Bar`, `Generic` all the way down was all that was needed.

```
data Foo = Foo  {fBar :: Bar}
derive instance genericFoo :: Generic Foo 
instance asForeignFoo :: AsForeign Foo where
  write = toForeignGeneric defaultOptions

data Bar = Bar  {…}
derive instance genericBar :: Generic Bar 
```

**Comment by paf31** [comment]
Oh I see, you're referring to the version based on the `purescript-generics`. Yes, that version was replaced with this one, because `purescript-generics` fails to handle cases where there is no `Generic` instance on a field type, like `Map`s or `DateTime`s.

You might like to consider `argonaut` instead, since I believe that still has a `purescript-generics` based API.

Alternatively, you could always fork this library from the tag you were using.

**Comment by wereHamster** [comment]
I don't care which version of generics I have to use, whether it's the old one or new one, I don't care. But I have a /lot/ of types that I need to serialize, and I was relying on `Generic` (alone) to do the job for me. Not much boilerplate was required besides a single `derive instance genericXxx` for each type. And since most basic data types have a `Generic` instance, that was perfect.

With the new version of Data.Foreign.Generic, I'd have to write a lot more code (`Decode` / `Encode` instances) and even have to change my own types (because there is no such instance for `Maybe` and other basic types, so essentially I'd have to make my own newtype wrappers around those).

Is there a technical reason why `Encode` / `Decode` instances are required now? Maybe the new `Generic` is not powerful enough?

**Comment by paf31** [comment]
> Is there a technical reason why Encode / Decode instances are required now? 

Yes, `generics-rep` only handles a single level of structure, and delegates to instances for types of record fields or data constructor arguments, where `generics` assumes every level has a `Generic` instance, down to the leaves of the tree. The `generics` approach means everything has to be `Generic`, so it's an all-or-nothing thing, whereas `generics-rep` is more composable - it lets each type define its own instances which don't need to be defined in terms of `Generic`.

> With the new version of Data.Foreign.Generic, I'd have to write a lot more code

But all of the new code can be written in terms of `genericDecode` and `genericEncode`, right?

> because there is no such instance for Maybe and other basic types

What other basic types? I'm happy to discuss adding instances for `Maybe`.

There is another option here, which is to try to support both flavors of generic programming in this library, but that depends on some work I need to finish in `generics-rep`, to add and derive old `Generic` in terms of new `Generic`.

**Comment by martyall** [comment]
I would also like express support for adding instances for `Maybe`. In my case `NullOrUndefined` is going to require some adapter boilerplate in several places, and from my library's point of view it's not an important distinction -- I only care if it's there or not.

**Comment by kevinbarabash** [comment]
I noticed there's a `GenericEncode` type class.  I was hoping that I could define instances of this type class instead of `Encode` so that I could pass custom options to the entire tree.  By relying on `Encode` I'm forced to embed my choice of options into the `Encode` instances.
