### ISSUE TITLE
Transform function for record field names

### ISSUE THREAD

**Issue by jacereda** [paf31/purescript-foreign-generic#31]
Would it be a good idea to add a `fieldTransform` function to `Options`? 

With that in place, things like the `attributes` record in the following could be handled easily.

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#meshes

**Comment by jacereda** [comment]
That link isn't working properly, this is the problematic record:

```
                    "attributes": {
                        "NORMAL": 23,
                        "POSITION": 22,
                        "TANGENT": 24,
                        "TEXCOORD_0": 25
                    },
```

**Comment by paf31** [comment]
👍 Sounds like a good idea.

**Comment by jacereda** [comment]
Looks like that would imply passing down `Options` to `encodeFields`? Is that OK?

**Comment by paf31** [comment]
Yes, I think so.
