### ISSUE TITLE
readProp >>= decode helper?

### ISSUE THREAD

**Issue by mjhoy** [paf31/purescript-foreign-generic#36]
Currently, `readProp k f >>= decode` (which seems common usage?) fails with, for example:

```
Type mismatch: expected String, found Null
```

If you have a complex object you're decoding, for instance, it's not a particularly helpful message. Since we have the key :: String available, maybe it's reasonable to have a helper that will include the key provided in the error message?

My hacky version I wrote to help me debug something:

```purescript
readDecodeProp ::
  forall a.
  Decode a =>
  String ->
  Foreign ->
  ExceptT (NonEmptyList ForeignError) Identity a
readDecodeProp k f =
  withExceptT annotate $ readProp k f >>= decode
  where
    annotate list = list <> (NEL.singleton $ ForeignError $ "Failed at key: " <> k)
```

Just an idea. And maybe there's already a helper or better way of writing this that already exists?

**Comment by paf31** [comment]
The generic decoder does something like this now. I think we should add a `withProp` function to `foreign` to do what you're describing.
