### ISSUE TITLE
should maybeAsNull be the default?

### ISSUE THREAD

**Issue by hdgarrood** [paf31/purescript-foreign-generic#9]
because I've just realised it breaks for `Maybe (Maybe a)` - `Nothing` and `Just Nothing` both get mapped to `null`. This behaviour is potentially useful in some cases, but I think it should probably be opt-in, with a warning in the docs.

**Comment by paf31** [comment]
This option will be removed in the next version, in favor of using `NullOrUndefined`, so I'll close this, but thanks.
